version: "3.6"
services:
  db:
    image: postgres:13.2-alpine
    env_file:
      - .env
    volumes:
      - mppm-db-data:/var/lib/postgresql/data
    ports:
      - "5432"
  mppm:
    image: qbonaventure/mppm:0.2.1
    tty: true
    env_file:
      - .env
    volumes:
      - mppm-data:/opt/mppm/game_servers
    ports:
      - "${MPPM_PORT}:${MPPM_PORT}"
      - "2350-2400:2350-2400"
      - "2350-2400:2350-2400/udp"
      - "3450-3500:3450-3500"
      - "3450-3500:3450-3500/udp"
    depends_on:
      - db
volumes:
  mppm-data:
    external: true
  mppm-db-data:
    external: true
